# -*- coding: utf-8 -*-
"""Assignment 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_wofRDKrY0ZQdkpW5Fvdx3tcvZaLAja
"""

# Install required library
!pip install xgboost

import pandas as pd
import numpy as np

# Upload data.csv manually before running this
df = pd.read_csv("data.csv")

print("Shape:", df.shape)
df.head()

"""Target variable: Bankrupt?

Positive class: 1 (bankrupt company)

This is a highly imbalanced dataset (~3% bankrupt cases).

Business problem: Missing a bankrupt company (false negative) is worse than flagging a healthy one.

Primary metric:
- PR-AUC (for discrimination)

Calibration metric:
- Brier Score (for probability quality)

"""

print(df['Bankrupt?'].value_counts())
print(df['Bankrupt?'].value_counts(normalize=True))

print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='Bankrupt?', data=df)
plt.title("Target Distribution")
plt.show()

"""Add observation (Markdown):

Only 3% bankrupt - dataset is imbalanced - accuracy is not useful
"""

from sklearn.model_selection import train_test_split

X = df.drop(columns=['Bankrupt?'])
y = df['Bankrupt?']

# 70/15/15 split
X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=0.15, stratify=y, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=0.1765, stratify=y_temp, random_state=42)

print("Train size:", X_train.shape)
print("Validation size:", X_val.shape)
print("Test size:", X_test.shape)

from sklearn.linear_model import LogisticRegression

results = []

model1 = LogisticRegression(max_iter=1000)
res1 = evaluate_model(model1, X_train, y_train, X_val, y_val)

res1.update({"exp_id":1, "model":"Logistic", "feature_set":"A"})
results.append(res1)

"""Experiment 1: Logistic Regression


"""

from sklearn.metrics import (
    average_precision_score, roc_auc_score,
    brier_score_loss, precision_score, recall_score, f1_score
)

def evaluate_model(model, X_train, y_train, X_val, y_val, threshold=0.5):

    model.fit(X_train, y_train)

    train_probs = model.predict_proba(X_train)[:,1]
    val_probs = model.predict_proba(X_val)[:,1]

    train_pr = average_precision_score(y_train, train_probs)
    val_pr = average_precision_score(y_val, val_probs)

    val_roc = roc_auc_score(y_val, val_probs)
    val_brier = brier_score_loss(y_val, val_probs)

    val_preds = (val_probs >= threshold).astype(int)

    precision = precision_score(y_val, val_preds)
    recall = recall_score(y_val, val_preds)
    f1 = f1_score(y_val, val_preds)

    return {
        "train_pr_auc": train_pr,
        "val_pr_auc": val_pr,
        "val_roc_auc": val_roc,
        "val_brier": val_brier,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "overfit_gap": train_pr - val_pr
    }

"""Experiment 2: XGBoost Baseline"""

from xgboost import XGBClassifier

model2 = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
res2 = evaluate_model(model2, X_train, y_train, X_val, y_val)

res2.update({"exp_id":2, "model":"XGB_base", "feature_set":"A"})
results.append(res2)

"""Experiment 3: Imbalance Handling"""

scale = (len(y_train) - sum(y_train)) / sum(y_train)

model3 = XGBClassifier(scale_pos_weight=scale)
res3 = evaluate_model(model3, X_train, y_train, X_val, y_val)

res3.update({"exp_id":3, "model":"XGB_weighted", "feature_set":"A"})
results.append(res3)

temp_model = XGBClassifier().fit(X_train, y_train)

importances = temp_model.feature_importances_
top_features = X.columns[np.argsort(importances)[-20:]]

X_train_B = X_train[top_features]
X_val_B = X_val[top_features]

"""Experiment 4: Tuned XGBoost"""

model4 = XGBClassifier(
    max_depth=4,
    learning_rate=0.05,
    n_estimators=300,
    subsample=0.8,
    colsample_bytree=0.8
)

res4 = evaluate_model(model4, X_train, y_train, X_val, y_val)

res4.update({"exp_id":4, "model":"XGB_tuned", "feature_set":"A"})
results.append(res4)

"""Experiment 5: Feature Set B"""

model5 = XGBClassifier()

res5 = evaluate_model(model5, X_train_B, y_train, X_val_B, y_val)

res5.update({"exp_id":5, "model":"XGB_top20", "feature_set":"B"})
results.append(res5)

results_df = pd.DataFrame(results)
results_df

model3 = XGBClassifier(scale_pos_weight=scale)

final_model = model3  # example (choose your best)

final_model.fit(X_train, y_train)

test_probs = final_model.predict_proba(X_test)[:,1]

from sklearn.metrics import confusion_matrix

threshold = 0.3
test_preds = (test_probs >= threshold).astype(int)

confusion_matrix(y_test, test_preds)

from sklearn.metrics import PrecisionRecallDisplay

PrecisionRecallDisplay.from_predictions(y_test, test_probs)

from sklearn.metrics import (
    average_precision_score, roc_auc_score,
    brier_score_loss, precision_score, recall_score, f1_score,
    confusion_matrix
)

final_model.fit(X_train, y_train)

test_probs = final_model.predict_proba(X_test)[:,1]

threshold = 0.3  # or 0.5 if you kept default
test_preds = (test_probs >= threshold).astype(int)

print("Test PR-AUC:", average_precision_score(y_test, test_probs))
print("Test ROC-AUC:", roc_auc_score(y_test, test_probs))
print("Test Brier:", brier_score_loss(y_test, test_probs))
print("Precision:", precision_score(y_test, test_preds))
print("Recall:", recall_score(y_test, test_preds))
print("F1:", f1_score(y_test, test_preds))

print("Confusion Matrix:\n", confusion_matrix(y_test, test_preds))

from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

prob_true, prob_pred = calibration_curve(y_test, test_probs, n_bins=10)

plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0,1],[0,1],'--')
plt.title("Calibration Curve")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

importance = final_model.feature_importances_
feat_names = X_train.columns

imp_df = pd.DataFrame({"feature": feat_names, "importance": importance})
imp_df = imp_df.sort_values(by="importance", ascending=False).head(10)

plt.barh(imp_df["feature"], imp_df["importance"])
plt.gca().invert_yaxis()
plt.title("Top Features")
plt.show()

"""The most important feature is Total debt/Total net worth, which has the highest importance score in the model.
This makes sense because companies with higher debt compared to their net worth are more likely to face financial distress and bankruptcy.
However, feature importance does not show causal relationships and does not capture interactions between variables, so results should be interpreted with caution.
"""

results_df

results_df["selected_finalist"] = "No"

results_df.loc[results_df["exp_id"] == 3, "selected_finalist"] = "Yes"

results_df

